apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
  name: {{ include "mosquitto.fullname" . }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "mosquitto.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mosquitto.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - image: "eclipse-mosquitto:{{ .Chart.AppVersion }}"
        name: mosquitto
        ports:
        - containerPort: 1883
          name: mqtt
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 10m
            memory: 10Mi
        livenessProbe:
            tcpSocket:
              port: mqtt
        readinessProbe:
            tcpSocket:
              port: mqtt
      volumes:
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "mosquitto.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end -}}