apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
  name: {{ include "mosquitto.fullname" . }}
spec:
  podSelector:
    matchLabels:
      {{- include "mosquitto.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 1883