apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
  name: {{ include "mosquitto.fullname" . }}
spec:
  ports:
  - name: mqtt
    port: 1883
    targetPort: mqtt
  selector:
    {{- include "mosquitto.selectorLabels" . | nindent 4 }}
  type: LoadBalancer