apiVersion: v1
kind: Service
metadata:
  name: {{ include "unifi.fullname" . }}-tcp
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ include "unifi.fullname" . }}
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
      name: http
    - port: 8443
      targetPort: https
      name: https
    - port: 6789
      targetPort: speedtest
      name: speedtest
  selector:
    {{- include "unifi.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "unifi.fullname" . }}-udp
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ include "unifi.fullname" . }}
spec:
  type: LoadBalancer
  ports:
    - port: 10001
      targetPort: discovery
      name: discovery
      protocol: UDP
    - port: 3478
      targetPort: stun
      name: stun
      protocol: UDP
  selector:
    {{- include "unifi.selectorLabels" . | nindent 4 }}