apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "openldap.fullname" . }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "openldap.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 389
