apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
  name: {{ include "openldap.fullname" . }}
type: Opaque
data:
  LDAP_ADMIN_PASSWORD: {{ .Values.adminUser.password | b64enc }}
  LDAP_CONFIG_PASSWORD: {{ .Values.configUser.password | b64enc }}
  LDAP_READONLY_USER_PASSWORD: {{ .Values.readOnlyUser.password | b64enc }}