apiVersion: v1
kind: Service
metadata:
  name: {{ include "openldap.fullname" . }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 389
      targetPort: ldap
      name: ldap
  selector:
    {{- include "openldap.selectorLabels" . | nindent 4 }}
