apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "nodered.labels" . | nindent 4 }}
  name: {{ include "nodered.fullname" . }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "nodered.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nodered.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: "nodered/node-red:{{ .Chart.AppVersion }}-minimal"
        name: nodered
        ports:
        - name: http
          containerPort: 1880
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
        livenessProbe:
          httpGet:
            port: http
            path: /
        readinessProbe:
          httpGet:
            port: http
            path: /
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
{{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "nodered.fullname" .) }}
{{- else }}
        emptyDir: {}
{{- end -}}