apiVersion: v1
kind: Service
metadata:
  name: {{ template "traefik.fullname" . }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    {{- include "traefik.selectorLabels" . | nindent 4 }}
  ports:
  - port: 443
    name: https
    targetPort: https
  - port: 80
    name: http
    targetPort: http
