{{- if not .Values.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "pi-hole.labels" . | nindent 4 }}
  name: {{ include "pi-hole.fullname" . }}
type: Opaque
data:
  {{- if .Values.admin.password }}
  password: {{ .Values.admin.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
{{- end }}