apiVersion: v1
kind: Service
metadata:
  name: {{ include "pi-hole.fullname" . }}
  labels:
    {{- include "pi-hole.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ include "pi-hole.fullname" . }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    {{- include "pi-hole.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pi-hole.fullname" . }}-dns-tcp
  labels:
    {{- include "pi-hole.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ include "pi-hole.fullname" . }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 53
      protocol: TCP
      targetPort: dns-tcp
      name: dns-tcp
  selector:
    {{- include "pi-hole.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pi-hole.fullname" . }}-dns-udp
  labels:
    {{- include "pi-hole.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ include "pi-hole.fullname" . }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 53
      protocol: UDP
      targetPort: dns-udp
      name: dns-udp
  selector:
    {{- include "pi-hole.selectorLabels" . | nindent 4 }}