apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "thelounge.labels" . | nindent 4 }}
  name: {{ include "thelounge.fullname" . }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "thelounge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "thelounge.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: "thelounge/thelounge:{{ .Chart.AppVersion }}"
        name: thelounge
        ports:
        - containerPort: 9000
          name: http
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
        livenessProbe:
          httpGet:
            port: http
            path: /
        readinessProbe:
          httpGet:
            port: http
            path: /
        volumeMounts:
          - name: data
            mountPath: /var/opt/thelounge
      volumes:
      - name: data
{{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "thelounge.fullname" .) }}
{{- else }}
        emptyDir: {}
{{- end -}}