{{- if .Values.ingress.enabled -}}
{{- $fullName := include "thelounge.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "thelounge.labels" . | nindent 4 }}
{{- if .Values.ingress.clusterIssuer }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer | quote }}
{{- end}}
spec:
{{- if .Values.ingress.clusterIssuer }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ printf "%s-tls" $fullName }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
{{- end }}
