apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  name: {{ include "keycloak.fullname" . }}
type: Opaque
data:
  KEYCLOAK_PASSWORD: {{ .Values.keycloak.password | b64enc }}
  DB_PASSWORD: {{ .Values.database.password | b64enc }}