apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "minecraft-bedrock.labels" . | nindent 4 }}
  name: {{ include "minecraft-bedrock.fullname" . }}
data:
  server.properties: |-
    server-name={{ .Values.minecraft.serverName }}
    gamemode=survival
    difficulty={{ .Values.minecraft.difficulty }}
    allow-cheats={{ .Values.minecraft.allowCheats }}
    max-players=10
    online-mode=true
    white-list=false
    server-port=19132
    server-portv6=19133
    view-distance=32
    tick-distance=4
    player-idle-timeout=30
    max-threads=8
    level-name={{ .Values.minecraft.levelName }}
    level-seed={{ .Values.minecraft.levelSeed }}
    default-player-permission-level=visitor
    texturepack-required=false
    content-log-file-enabled=false
    compression-threshold=1
    server-authoritative-movement=true
    player-movement-score-threshold=20
    player-movement-distance-threshold=0.3
    player-movement-duration-threshold-in-ms=500
    correct-player-movement=false