apiVersion: v2
name: openldap
description:  OpenLDAP Software is an open source implementation of the Lightweight Directory Access Protocol.
type: application
version: 0.1.0
appVersion: 1.3.0
home: https://www.openldap.org/
icon: file://../logo.png