nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: chart-example.local
  tls:
    enabled: true
    clusterIssuer: "letsencrypt-staging"
    secretName: "xoa-tls"

resources:
  requests:
    cpu: 100m
    memory: 150Mi
  limits:
    cpu: 500m
    memory: 250Mi

persistence:
  enabled: false
  # storageClassName: default
  accessModes:
    - ReadWriteOnce
  size: 2Gi
  # existingClaim:

backup:
  enabled: true
  # storageClassName: default
  accessModes:
    - ReadWriteOnce
  size: 2Gi
  # existingClaim:

redisUrl: redis://redis:6379/0